import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/components/Navbar";
import { AlumProvider } from "@/context/AlumContext";
import { NewsLetterProvider } from "@/context/NewsLetterContext";
import { EventProvider } from "@/context/EventContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <AlumProvider>
          <NewsLetterProvider>
            <EventProvider>
              <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
              >
                <div className="bg-blue-200 ">
                  <Navbar />
                </div>
                {children}
              </body>
            </EventProvider>
          </NewsLetterProvider>
        </AlumProvider>
      </AuthProvider>
    </html>
  );
}
