import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/components/Navbar";
import { AlumProvider } from "@/context/AlumContext";
import { NewsLetterProvider } from "@/context/NewsLetterContext";
import { JobOfferProvider } from "@/context/JobOfferContext";
import { AnnouncementProvider } from "@/context/AnnouncementContext";
import { EventProvider } from "@/context/EventContext";

import { DonationDriveProvider } from "@/context/DonationDriveContext";
import { BookmarkProvider } from "@/context/BookmarkContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <DonationDriveProvider>
          <BookmarkProvider>
            <JobOfferProvider>
              <AnnouncementProvider>
                <AlumProvider>
                  <NewsLetterProvider>
                    <EventProvider>
                      <body
                        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                      >
                        <div className="bg-blue-200 ">
                          <Navbar />
                        </div>
                        {children}
                      </body>
                    </EventProvider>
                  </NewsLetterProvider>
                </AlumProvider>
              </AnnouncementProvider>
            </JobOfferProvider>
          </BookmarkProvider>
        </DonationDriveProvider>
      </AuthProvider>
    </html>
  );
}
