import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/components/Navbar";
import { AlumProvider } from "@/context/AlumContext";
import { NewsLetterProvider } from "@/context/NewsLetterContext";
import { JobOfferProvider } from "@/context/JobOfferContext";
import { AnnouncementProvider } from "@/context/AnnouncementContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <JobOfferProvider>
          <AnnouncementProvider>
        <AlumProvider>
          <NewsLetterProvider>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <div className="bg-blue-200 ">
                <Navbar />
              </div>
              {children}
            </body>
          </NewsLetterProvider>
        </AlumProvider>
        </AnnouncementProvider>
        </JobOfferProvider>
      </AuthProvider>
    </html>
  );
}
